/**
 * Configuration version of all build dependencies
 */
object BuildDependenciesVersions {
    const val SHIMMER = "0.1.0"
    const val KOTLIN = "1.3.70"
    const val APPCOMPAT = "1.1.0"
    const val MATERIAL = "1.1.0"
    const val COROUTINES = "1.3.4"
    const val ROOM = "2.2.3"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.3.0-alpha02"
    const val LIFECYCLE = "2.1.0"
    const val CORE_KTX = "1.1.0"
    const val FRAGMENT_KTX = "1.2.0-alpha02"
    const val CONSTRAIN_LAYOUT = "1.1.3"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0-alpha02"
    const val PAGING = "2.1.1"
    const val DAGGER = "2.25.3"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.7.0"
    const val LOGGING = "4.2.2"
    const val MOSHI = "1.9.2"
    const val COIL = "0.8.0"
    const val CRASHLYTICS = "2.10.1"
    const val PLAY_CORE = "1.6.4"
    const val LEAKCANARY = "2.0"
    const val DATABINDING = "3.1.4"
    const val AUTO_SERVICE = "1.0-rc4"
    const val RX_JAVA_VERSION = "2.1.6"
    const val RX_ANDROID_VERSION = "2.0.1"
    const val JODA_TIME_VERSION = "2.9.9.4"
    const val JAVAX_ANNOTATION_VERSION = "1.0"
    const val JAVAX_INJECT_VERSION = "1"
    const val RETROFIT_RX_ADAPTER_VERSION = "2.3.0"
    const val OKHTTP3_LOGGING_INTERCEPTOR_VERSION = "3.9.0"
    const val LEAK_CANARY_VERSION = "1.5"
    const val PICASSO_VERSION = "2.71828"
    const val MULTIDEX = "2.0.0"
    const val MATERIAL_DESIGN_SPECS = "2.0.1"
    const val PICASSO_TRANSFORMATIONS = "2.2.1"
    const val CIRCLE_IMAGE_VIEW = "2.2.0"
    const val STETHO = "1.5.0"
    const val RXBINDING_PLATFORM = "3.0.0"
    const val FLOW_BINDING = "0.10.1"
    const val HTML_TEXTVIEW = "3.9"
    const val PRO_PROGRESS_VIEWS = "1.1"

    // Tests
    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13"
    const val ROBOELECTRIC = "4.3.1"
    const val MOCKITO = "2.2.0"
    const val MOCKK = "1.9.3"
    const val ASSERTJ = "3.14.0"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.2.0-alpha02"
    const val MOCK_WEB_SERVER = "4.2.2"
    const val KONVEYOR_VERSION = "1.0.3"
    const val TRUTH = "1.0.1"

}
